#!/bin/sh

CYGPATH ()
{
    if command -v cygpath >/dev/null 2>&1; then
        cygpath -w "$1"
    else
        echo "$1"
    fi
}

if ! command -v fpc >/dev/null 2>&1; then
    echo "No Free Pascal on the system" >&2
    exit 1
fi

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1

SETTING="${CWD}/setting.sh"

if [ -f "$SETTING" ]; then
    . "$SETTING"
else
    echo "Error: Unable to load the repository setting: $SETTING" >&2
    exit 1
fi

mkdir -p "$LIB_DIR"
mkdir -p "$OBJ_DIR"

COMPILE_MODE=$(echo "$1" | tr '[:lower:]' '[:upper:]')
if [ "$COMPILE_MODE" = "DEBUG" ]; then
    COMPILER_FLAG="-dDEBUG -g -gl -Cr -Ct -Co -Ci -Sa"
else
    COMPILER_FLAG="-O2 -Xs -CX -XX"
fi

FPC_FLAGS="${FPC_FLAGS:-}"

set --
[ -n "$FPC_FLAGS" ]     && set -- $@ $FPC_FLAGS
[ -n "$COMPILER_FLAG" ] && set -- $@ $COMPILER_FLAG

fpc "$@" \
    "-o$(CYGPATH "${LIB_DIR}/${DYNAMIC_LIBRARY}")" \
    "-Fu$(CYGPATH "${SRC_DIR}")" \
    "-Fi$(CYGPATH "${INCLUDE_DIR}")" \
    "-FU$(CYGPATH "${OBJ_DIR}")" \
    "-FE$(CYGPATH "${LIB_DIR}")" \
    "$(CYGPATH "${SRC_DIR}/${ENTRY}")"