#!/bin/sh

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1

if [ -f "${CWD}/setting.sh" ]; then
    . "${CWD}/setting.sh"
else
    echo "Error: setting.sh not found." >&2
    exit 1
fi

FORMATER="${CWD}/tools/bin/format"

if [ ! -x "$FORMATER" ]; then
    echo "Error: Formatter not executable: $FORMATER" >&2
    exit 1
fi

if [ ! -d "${SRC_DIR}" ]; then
    echo "Error: the source directory does not exist: ${SRC_DIR}" >&2
    exit 1
fi

while IFS= read -r file; do
    if ! "$FORMATER" "$file"; then
        echo "Error: Stop execution. Formatting failed on: $file" >&2
        exit 1
    fi
done << EOF
$(find "${SRC_DIR}" "${TEST_DIR}" -type f)
EOF

echo "All files formatted successfully."
